### PR TITLE
Avoid unnecessarily casting to Tag.Identified to obtain the identifier for tag predicates

### LINKED ISSUE #174: /cfinditem #minecraft:[tag name] errors out with java.lang.ClassCastException
When running, for example `/cfinditem #minecraft:shulker_boxes`, the command prints "An unexpected error occurred trying to execute that command" to chat and the following to the game log:

<details>

<summary> Log when running command </summary>

```
[04:26:32] [main/INFO]: [CHAT] An unexpected error occurred trying to execute that command
[04:26:32] [main/INFO]: [STDERR]: java.lang.ClassCastException: net.minecraft.class_5394 cannot be cast to net.minecraft.class_3494$class_5123
[04:26:32] [main/INFO]: [STDERR]: 	at net.earthcomputer.clientcommands.command.arguments.ClientItemPredicateArgumentType.lambda$parse$2(ClientItemPredicateArgumentType.java:54)
[04:26:32] [main/INFO]: [STDERR]: 	at net.earthcomputer.clientcommands.command.arguments.ClientItemPredicateArgumentType$ClientItemPredicateArgument.create(ClientItemPredicateArgumentType.java:64)
[04:26:32] [main/INFO]: [STDERR]: 	at net.earthcomputer.clientcommands.command.FindItemCommand.findItem(FindItemCommand.java:76)
[04:26:32] [main/INFO]: [STDERR]: 	at net.earthcomputer.clientcommands.command.FindItemCommand.lambda$register$2(FindItemCommand.java:69)
[04:26:33] [main/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[04:26:33] [main/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[04:26:33] [main/INFO]: [STDERR]: 	at net.earthcomputer.clientcommands.command.ClientCommandManager.executeCommand(ClientCommandManager.java:54)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zka000$onSendChatMessage(class_746.java:1761)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:313)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:306)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:98)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:345)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:435)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:343)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:433)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:433)
[04:26:33] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[04:26:33] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[04:26:33] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[04:26:33] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:308)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1068)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[04:26:33] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:26:33] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:26:33] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
[04:26:33] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
[04:26:33] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:26:33] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:26:33] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:26:33] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[04:26:33] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[04:26:33] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[04:26:33] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
</details>

<details>

<summary> System Details from /debug report </summary>

```
-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_265, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
  Memory: 1863490560 bytes (1777 MB) / 4831838208 bytes (4608 MB) up to 4831838208 bytes (4608 MB)
  CPUs: 6
  JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4608m -Xmx4608m
  Suspected Mods: Unknown
  Fabric Mods: attributefix: Attribute Fix {FABRIC} 1.0.0
               autoconfig1u: Auto Config v1 Updated 3.3.1
               carpet: Carpet Mod in Fabric 1.4.21
               carpet-extra: Carpet Extra 1.4.16
               clientcommands: Client Commands 2.4.9
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-config2: Cloth Config v4 4.8.2
               fabric: Fabric API 0.26.0+1.16
               fabric-api-base: Fabric API Base 0.2.0+ba858fb83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+6a2618f53a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.8
               itemscroller: Item Scroller 0.15.0-dev.20201103.183933
               litematica: Litematica 0.0.0-dev.20201103.184101
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               minecraft: Minecraft 1.16.4
               minihud: MiniHUD 0.19.0-dev.20201103.184029
               modmenu: Mod Menu unspecified
               multiconnect-api: MultiConnect API 1.3.9
               no_fog: No Fog 1.0.2-beta.1+1.16.2
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
               tweakeroo: Tweakeroo 0.10.0-dev.20201110.132827
               xaerominimap: Xaero's Minimap 20.27.2
               xaeroworldmap: Xaero's World Map 1.11.0
```
</details>

### PR DESCRIPTION
**Pull request by haykam821**
Fixes #174

### CODE REVIEW

File: src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientItemPredicateArgumentType.java [hunk 1]
```diff
@@ -51,11 +51,11 @@ public ClientItemPredicateArgument parse(StringReader reader) throws CommandSynt
         } else {
             Identifier tagId = itemReader.getId();
             return ctx -> {
-                @SuppressWarnings("ConstantConditions") Tag.Identified<Item> tag = (Tag.Identified<Item>) MinecraftClient.getInstance().getNetworkHandler().getTagManager().getItems().getTag(tagId);
+                @SuppressWarnings("ConstantConditions") Tag<Item> tag = MinecraftClient.getInstance().getNetworkHandler().getTagManager().getItems().getTag(tagId);
```
Comment (Earthcomputer) [inline src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientItemPredicateArgumentType.java:54]: Is `@SuppressWarnings("ConstantConditions")` still needed?

Comment (James103) [reply src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientItemPredicateArgumentType.java:54]: > Is `@SuppressWarnings("ConstantConditions")` still needed?

In other words, do you get any warnings related to `ConstantConditions` around here if you remove the `@SuppressWarnings("ConstantConditions")` from that line? If not, the suppressor can be removed. If you do get such warnings, the suppressor should remain as is.

Comment (Earthcomputer) [reply src/main/java/net/earthcomputer/clientcommands/command/arguments/ClientItemPredicateArgumentType.java:54]: Apparently it still has the effect of avoiding a null check

**Review by Earthcomputer — APPROVED** [review]
