### PR TITLE
Fix recursive alias detection

### LINKED ISSUE #645: Cant run alias command after running it once
You cant run a alias after running it once

## steps to reproduce
1. make a alias via the `calias` command
2. run the alias twice

### PR DESCRIPTION
**Pull request by mygizli04**
Fixes #645 

When trying to detect whether or not an alias is recursive, it's added to an array of seen aliases. However this array was never cleared meaning after an alias is executed, it cannot be executed again with the error 'Recursive alias "[name of alias]"' appearing in chat despite there being no recursion.

I've confirmed that this issue does not occur on 2.8.18 but occurs after 2.8.19, after the recursion detection was added.

This pull request fixes the issue by removing the alias from the list of seen aliases after the command is completed.

### CODE REVIEW

**Review by Earthcomputer — CHANGES_REQUESTED** [review]
Thanks for the PR! You can use [try-finally](https://docs.oracle.com/javase%2Ftutorial%2F/essential/exceptions/finally.html) in Java to make this a bit cleaner

**Comment by mygizli04** [comment]
Thanks for taking the time to respond, I'm not sure if I understood exactly what you mean but I wrapped the entire function in a try-finally block. If that's not what you meant please let me know.

**Comment by Earthcomputer** [comment]
This is almost good, although the try-finally should start after the addition of the alias key to the set.

**Comment by mygizli04** [comment]
Alright, how about now?

File: src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java [hunk 1]
```diff
@@ -78,40 +78,45 @@ private static int executeAliasCommand(FabricClientCommandSource source, String
         if (cmd == null) {
             throw NOT_FOUND_EXCEPTION.create(aliasKey);
         }
-
+
```
Comment (Earthcomputer) [inline src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java]: Can you remove this extra indentation?

**Review by Earthcomputer — CHANGES_REQUESTED** [review]
One more thing and we're good to go.

File: src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java (hunk 1 above)
Comment (mygizli04) [reply src/main/java/net/earthcomputer/clientcommands/command/AliasCommand.java]: Ah, my bad. Fixed now.

**Review by Earthcomputer — APPROVED** [review]
